# Generated by Django 6.0 on 2025-12-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_techfest_participants_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
                ('subscription', models.CharField(max_length=12)),
                ('fullname', models.CharField(max_length=12)),
                ('residence', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=12)),
                ('parent', models.EmailField(max_length=254)),
                ('displayname', models.CharField(max_length=12)),
                ('account', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='techfest_participants',
        ),
    ]
