# Generated by Django 6.0 on 2025-12-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_app_users_delete_techfest_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_users',
            name='last_login',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
