# Generated by Django 6.0 on 2025-12-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_app_users_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_users',
            name='displayname',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='app_users',
            name='fullname',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='app_users',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='app_users',
            name='source',
            field=models.CharField(max_length=30),
        ),
    ]
